name: muslim
description: muslim-pro start kit app.

publish_to: "none"

version: 2.4.0+18

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: 3.24.3


dependencies:
  # UI Components
  arabic_numbers: ^1.0.0

  # Audio & Media
  audioplayers: ^6.4.0
  auto_size_text: ^3.0.0
  day_night_time_picker: ^1.3.1
  flutter_colorpicker: ^1.1.0
  flutter_slidable: ^4.0.0
  scrollable_positioned_list: ^0.3.8
  sleek_circular_slider: ^2.1.0

  # State Management
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  rxdart: ^0.28.0

  # Notifications
  awesome_notifications: ^0.10.0
  flutter_local_notifications: ^19.2.1

  # UI & Navigation
  bot_toast: ^4.1.3
  flutter_zoom_drawer: ^3.2.0
  capture_widget:
    path: packages/capture_widget

  # Network & HTTP
  dio: ^5.7.0
  http: ^1.4.0

  # Core Flutter
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6

  # Utilities
  enum_to_string: ^2.2.1
  file_picker: ^10.1.9
  fluttertoast: ^8.2.12
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.2
  get_storage: ^2.1.1
  intl: ^0.20.2
  material_design_icons_flutter: ^7.0.7296
  path: ^1.9.0
  path_provider: ^2.1.5
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  vibration: ^3.1.3
  wakelock_plus: ^1.3.2
  window_manager: ^0.5.0

  # Database
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.5

  # Firebase
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6

  # Quran specific dependencies
  cached_network_image: ^3.4.1
  integration_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.8.0

flutter_native_splash:
  android: true
  ios: true
  #  web: true
  color: "#303030"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/json/
    - assets/images/
    - assets/quran/
    - assets/sounds/
    - assets/db/
    - assets/data/

  fonts:
    - family: Uthmanic
      fonts:
        - asset: assets/fonts/uthmanic_hafs_ver12.otf
    - family: Uthmanic2
      fonts:
        - asset: assets/fonts/UthmanicHafs_v2-1.ttf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
    - family: Marhey
      fonts:
        - asset: assets/fonts/Marhey-Regular.ttf
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-Regular.ttf
    - family: ElMessiri
      fonts:
        - asset: assets/fonts/ElMessiri-Regular.ttf
    - family: Harmattan
      fonts:
        - asset: assets/fonts/Harmattan-Regular.ttf
    - family: Lateef
      fonts:
        - asset: assets/fonts/Lateef-Regular.ttf
    - family: Mada
      fonts:
        - asset: assets/fonts/Mada-Regular.ttf
    - family: Changa
      fonts:
        - asset: assets/fonts/Changa-Regular.ttf
    - family: ArefRuqaa
      fonts:
        - asset: assets/fonts/ArefRuqaa-Regular.ttf
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
    - family: NotoNastaliqUrdu
      fonts:
        - asset: assets/fonts/NotoNastaliqUrdu-Regular.ttf
    - family: Lalezar
      fonts:
        - asset: assets/fonts/Lalezar-Regular.ttf
    - family: ReemKufi
      fonts:
        - asset: assets/fonts/ReemKufi-Regular.ttf
    - family: Rakkas
      fonts:
        - asset: assets/fonts/Rakkas-Regular.ttf
    - family: quran
      fonts:
        - asset: assets/fonts/HafsSmart_08.ttf
    - family: me_quran
      fonts:
        - asset: assets/fonts/me_quran.ttf


flutter_intl:
  enabled: true
